url: 'https://wallingford-emergency-foodbank.github.io'
baseurl: '/'
title: 'Wallingford Emergency Foodbank'

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

sass:
load_paths:
  - _sass
  - node_modules

include: ["node_modules/tailwindcss"]
